version: "3"

services:
  worker:
      build: .
      volumes:
        - ./:/code
      environment:
        - PUBLISHER_HOST=publisher
        - PUBLISHER_PORT=5690
      command: sleep 365d

  publisher:
      build: .
      volumes:
        - ./:/code
      environment:
        - PUBLISHER_HOST=publisher
        - PUBLISHER_PORT=5690
      ports:
        - "5690:5690"
      expose:
        - "5690"
      command: sleep 365d
      links:
        - worker